Test feature branch (#2)
* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update config files

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Misc updates

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

* chore: Update circleci config.yml

Co-authored-by: Arthur Ezenwanne <Arthur Ezenwanne>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,39 +3,48 @@ version: 2.1
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    # parameters:
-      # Add parameter here 
-      # ${CIRCLE_WORKFLOW_ID:0:7}  
-      # id: 
-      #   type: string
+    parameters:  
+      workflow_id: 
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
+            pwd
             # Your code here
-            # aws s3 rb s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --force
-            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
-            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
+            echo "Destroying environment: << parameters.workflow_id >> "
+            aws s3 rb s3://udapeople-<< parameters.workflow_id >> --force
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
 
-  # revert-migrations:
-  #   description: Revert the last migration if successfully run in the current workflow.
-  #   # parameters:
-  #     # Add parameter here     
-  #   steps:
-  #     - run:
-  #         name: Revert migrations
-  #         # Add when this will run
-  #         command: |
-  #           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-  #           SUCCESS = 1
-  #           if(( $SUCCESS==1 )); 
-  #           then
-  #           #  cd ~/project/backend
-  #           #  npm install
-  #           #  Add revert code here. You can find this in the Getting Started section.
-  #             exit 1
-  #           fi
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:  
+      workflow_id: 
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}    
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            pwd
+            echo 'Hello Test'
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            export SUCCESS=$(curl --insecure  "https://kvdb.io/KiP8dNxt1g1ZAyrgEnwPWk/migration_<< parameters.workflow_id >>")
+            echo ${SUCCESS}
+            if [ ${SUCCESS} = 1 ]
+            then
+                pwd
+                dir
+                cd /backend/
+                npm install
+                #  Add revert code here.
+                npm run migrations:revert
+                echo ${SUCCESS}
+            fi
             
 jobs:
   build-frontend:
@@ -49,6 +58,8 @@ jobs:
       - run:
           name: Build front-end
           command: |
+            pwd
+            dir
             # Your code here
             cd frontend
             npm install
@@ -67,6 +78,8 @@ jobs:
       - run:
           name: Back-end build
           command: |
+            pwd
+            dir
             # Your code here
             cd backend
             npm install
@@ -85,6 +98,8 @@ jobs:
       - run:
           name: Run Frontend unit tests
           command: |
+            pwd
+            dir
             # Your code here
             cd frontend
             npm install
@@ -100,6 +115,8 @@ jobs:
       - run:
           name: Run Backend unit tests
           command: |
+            pwd
+            dir
             # Your code here
             cd backend
             npm install
@@ -116,6 +133,8 @@ jobs:
       - run:
           name: Run Frontend audit tests
           command: |
+            pwd
+            dir
             # Your code here
             cd frontend
             npm install
@@ -134,6 +153,8 @@ jobs:
       - run:
           name: Run Backend audit tests
           command: |
+            pwd
+            dir
             # Your code here
             cd backend
             npm install
@@ -148,10 +169,17 @@ jobs:
     steps:
       # Checkout code from git
       - checkout
-      - run: npm install -y tar gzip
+      - run: 
+          name: Install dependencies
+          command: |
+            pwd
+            dir 
+            npm install -y tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
+            pwd
+            dir
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople \
@@ -161,6 +189,8 @@ jobs:
       - run:
           name: Ensure front-end infrastructure exist
           command: |
+            pwd
+            dir
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
@@ -170,12 +200,16 @@ jobs:
       - run:
           name: Add back-end ip to ansible inventory
           command: |
+            pwd
+            dir
             # Your code here
             aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
             --filters "Name=tag:project,Values=udapeople" \
             --output text >> ~/project/.circleci/ansible/inventory.txt
             # exit 1
+            pwd
+            dir
       - persist_to_workspace:
           root: ~/
           # root: .circleci/ansible
@@ -194,21 +228,25 @@ jobs:
           fingerprints: ["9b:34:78:6f:cb:95:cc:75:61:af:3a:3e:3a:bb:72:d3"]
       - attach_workspace:
           at: ~/
-          # at: /tmp/.circleci/ansible
       - run:
           name: Install dependencies
           command: |
+            pwd
+            ls
             # Your code here
             apk add --update --no-cache tar gzip ansible aws-cli
       - run:
           name: Configure server
           command: |
+            pwd
+            ls
             # Your code here
             cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml
+            pwd
+            ls
       - persist_to_workspace:
           root: ~/
-          # root: .circleci/ansible
           paths:
             - project/backend
       # Here's where you will add some code to rollback on failure   
@@ -219,94 +257,222 @@ jobs:
       - image: cimg/node:13.8.0
     steps:
       # Checkout code from git
+      - checkout
+      # - attach_workspace:
+      #     at: ~/
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            pwd
+            dir
+            # Your code here 
+            cd backend
+            npm install
+            # Run and save the migration output
+            npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
+            # exit 1
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to kvdb.io 
           command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+            pwd
+            dir
+            cat ~/project/backend/migrations_dump.txt
+            if grep -q "has been executed successfully" ~/project/backend/migrations_dump.txt ; then
+                echo Hello
+                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                curl --insecure "https://kvdb.io/KiP8dNxt1g1ZAyrgEnwPWk/migration_${CIRCLE_WORKFLOW_ID:0:7}" -d '1'
+                cat ~/project/backend/migrations_dump.txt
+                pwd
+                dir
+                # return 0
+            # else 
+            #     return 1
+            fi
+            # exit 1
+      # Here's where you will add some code to rollback on failure      
       - destroy-environment   
+      - revert-migrations    
 
-  # deploy-frontend:
-  #   docker:
-  #     # Docker image here that supports AWS CLI
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "${API_URL}"
-  #     - run:
-  #         name: Deploy frontend objects
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure      
-                    
-  # deploy-backend:
-  #   docker:
-  #     # Docker image here that supports Ansible
-  #   steps:
-  #     # Checkout code from git
-  #     # Add ssh keys with fingerprint
-  #     # attach workspace
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Deploy backend
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: cimg/aws:2022.11
+    steps:
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            pwd
+            dir
+            # your code here
+            # apk add --update --no-cache tar gzip nodejs npm aws-cli curl
+            npm update
+            npm install -y tar gzip nodejs npm aws-cli curl
+      - run:
+          name: Get backend url
+          command: |
+            pwd
+            dir
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects 
+          command: |
+            pwd
+            dir
+            # your code here
+            cd frontend
+            export NODE_OPTIONS=--openssl-legacy-provider
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            echo "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
+            # aws s3 cp dist s3://udapeople-buc-ogidi-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            # echo "s3://udapeople-buc-ogidi-${CIRCLE_WORKFLOW_ID:0:7}"            
+            pwd
+            dir
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations    
+                 
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.16
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["9b:34:78:6f:cb:95:cc:75:61:af:3a:3e:3a:bb:72:d3"]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            pwd
+            ls
+            # your code here
+            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible
+      - run:
+          name: Deploy backend
+          command: |
+            pwd
+            ls
+            # your code here
+            cd backend
+            npm install
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            pwd
+            ls
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is ------- $(cat inventory.txt)"
+            ansible-playbook -i inventory.txt deploy-backend.yml
+            pwd
+            ls
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations    
 
-  # smoke-test:
-  #   docker:
-  #     # Lightweight Docker image 
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+      # Lightweight Docker image       
+      - image: python:3.7-alpine3.16
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            pwd
+            ls
+            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible curl
+      - run:
+          name: Get backend url
+          command: |
+            pwd
+            ls
+            # your code here
+            # Fetch and prepare the BACKEND_IP env var
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+      - run:
+          name: Backend smoke test
+          command: |
+            pwd
+            ls
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
 
-  # cloudfront-update:
-  #   docker:
-  #     # Docker image here that supports AWS CLI
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Update cloudfront distribution
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                echo "Backend Smoke Test Success"
+                return 0
+            else
+                echo "Backend Smoke Test Failed"
+                return 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            pwd
+            ls
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+                echo "Frontend Smoke Test Success"
+                return 1
+            else
+                echo "Frontend Smoke Test Failed"
+                return 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations  
+      
+
+  cloudfront-update:
+    docker:
+      # Docker image here that supports AWS CLI
+      -  image: cimg/aws:2022.11
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            npm update
+            npm install -y tar gzip nodejs npm aws-cli curl
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            # your code here
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name InitialStack \
+            --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --tags project=udapeople
+      # Here's where you will add some code to rollback on failure  
+      - revert-migrations  
+      - destroy-environment
 
 # cleanup:
 #     docker:
@@ -350,12 +516,12 @@ workflows:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
-      # - deploy-backend:
-      #     requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
